# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSDemos' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  pod 'Masonry', '1.1.0'
  pod 'AFNetworking', :path => '../../AFNetworking'
  # Pods for iOSDemos

  target 'iOSDemosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSDemosUITests' do
    # Pods for testing
  end

end
